apiVersion: 2021-10-01
location: mexicocentral
name: aci-clyvocare-group
properties:
  osType: Linux
  restartPolicy: Always
  imageRegistryCredentials:
    - server: acrclyvo5seay.azurecr.io
      username: acrclyvo5seay
      password: 5z0vbarrA64rnkVcjbxRm82FYQGTHiC4i1l0MkHCSSvJA3KmrFFAJQQJ99CIACL3ha5Eqg7NAAACAZCRe3ol
  ipAddress:
    type: Public
    dnsNameLabel: clyvocare-api-5seay
    ports:
      - protocol: tcp
        port: 8080
      - protocol: tcp
        port: 1521
  containers:
    - name: oracle-db
      properties:
        image: gvenzl/oracle-xe:21-slim
        resources:
          requests:
            cpu: 1.0
            memoryInGB: 2.5
        environmentVariables:
          - name: ORACLE_PASSWORD
            value: "Oracle_123"
          - name: APP_USER
            value: "clyvocare"
          - name: APP_USER_PASSWORD
            value: "clyvo123"
        ports:
          - port: 1521
    - name: clyvocare-api
      properties:
        image: acrclyvo5seay.azurecr.io/clyvocare-api:v1
        resources:
          requests:
            cpu: 1.0
            memoryInGB: 1.5
        environmentVariables:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:oracle:thin:@127.0.0.1:1521/XEPDB1"
          - name: SPRING_DATASOURCE_USERNAME
            value: "system"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "Oracle_123"
        ports:
          - port: 8080
