
-- Projeto ClyvoCare
-- Sistema de plano de saúde para pets

SET SERVEROUTPUT ON SIZE UNLIMITED;
SET LINESIZE 200;


BEGIN
    FOR t IN (
        SELECT table_name FROM user_tables
        WHERE table_name IN (
            'TB_HEA_ERROR_LOG','TB_HEA_REMINDER','TB_HEA_CLINICAL_EVENT',
            'TB_CAD_SUBSCRIPTION','TB_CAD_SUB_STATUS','TB_CAD_PAYMENT_METHOD',
            'TB_CAD_PET','TB_CAD_CLINIC','TB_CAD_CITY','TB_CAD_STATE',
            'TB_CAD_BREED','TB_CAD_SPECIES','TB_CAD_PLAN','TB_CAD_OWNER'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE '||t.table_name||' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

-- =====================================================================
-- Tabelas de domínio (Lookup)
-- =====================================================================

CREATE TABLE TB_CAD_SPECIES (
    ID         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NAME       VARCHAR2(50)  NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE TB_CAD_BREED (
    ID         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    SPECIES_ID NUMBER(19) NOT NULL,
    NAME       VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_BREED_SPECIES    FOREIGN KEY (SPECIES_ID) REFERENCES TB_CAD_SPECIES(ID),
    CONSTRAINT UK_BREED_SPECIES_NM UNIQUE (SPECIES_ID, NAME)
);

CREATE TABLE TB_CAD_STATE (
    ID   NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    UF   VARCHAR2(2)      NOT NULL UNIQUE,
    NAME VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE TB_CAD_CITY (
    ID       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    STATE_ID NUMBER(19) NOT NULL,
    NAME     VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_CITY_STATE    FOREIGN KEY (STATE_ID) REFERENCES TB_CAD_STATE(ID),
    CONSTRAINT UK_CITY_STATE_NM UNIQUE (STATE_ID, NAME)
);

CREATE TABLE TB_CAD_PAYMENT_METHOD (
    ID   NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE TB_CAD_SUB_STATUS (
    ID   NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL UNIQUE
);

-- =====================================================================
-- Tabelas de negócio
-- =====================================================================

CREATE TABLE TB_CAD_OWNER (
    ID            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    CITY_ID       NUMBER(19)    NOT NULL,
    NAME          VARCHAR2(150) NOT NULL,
    CPF           VARCHAR2(14)  NOT NULL UNIQUE,
    EMAIL         VARCHAR2(150) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    PHONE         VARCHAR2(20)  NOT NULL,
    CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_OWNER_CITY FOREIGN KEY (CITY_ID) REFERENCES TB_CAD_CITY(ID)
);

CREATE TABLE TB_CAD_PLAN (
    ID            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NAME          VARCHAR2(50) NOT NULL UNIQUE,
    MONTHLY_VALUE NUMBER(10,2) NOT NULL,
    CONSTRAINT CK_PLAN_VALUE CHECK (MONTHLY_VALUE > 0)
);

CREATE TABLE TB_CAD_PET (
    ID         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    OWNER_ID   NUMBER(19)    NOT NULL,
    SPECIES_ID NUMBER(19)    NOT NULL,
    BREED_ID   NUMBER(19),
    NAME       VARCHAR2(100) NOT NULL,
    BIRTH_DATE DATE          NOT NULL,
    SEX        VARCHAR2(10)  CHECK (SEX IN ('MALE','FEMALE')),
    CONSTRAINT FK_PET_OWNER   FOREIGN KEY (OWNER_ID)   REFERENCES TB_CAD_OWNER(ID),
    CONSTRAINT FK_PET_SPECIES FOREIGN KEY (SPECIES_ID) REFERENCES TB_CAD_SPECIES(ID),
    CONSTRAINT FK_PET_BREED   FOREIGN KEY (BREED_ID)   REFERENCES TB_CAD_BREED(ID)
);

CREATE TABLE TB_CAD_SUBSCRIPTION (
    ID                 NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PET_ID             NUMBER(19)   NOT NULL,
    PLAN_ID            NUMBER(19)   NOT NULL,
    STATUS_ID          NUMBER(19)   NOT NULL,
    PAYMENT_METHOD_ID  NUMBER(19)   NOT NULL,
    START_DATE         DATE DEFAULT SYSDATE,
    CONTRACTED_VALUE   NUMBER(10,2) NOT NULL,
    CONSTRAINT FK_SUB_PET     FOREIGN KEY (PET_ID)            REFERENCES TB_CAD_PET(ID),
    CONSTRAINT FK_SUB_PLAN    FOREIGN KEY (PLAN_ID)           REFERENCES TB_CAD_PLAN(ID),
    CONSTRAINT FK_SUB_STATUS  FOREIGN KEY (STATUS_ID)         REFERENCES TB_CAD_SUB_STATUS(ID),
    CONSTRAINT FK_SUB_PAYMENT FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES TB_CAD_PAYMENT_METHOD(ID),
    CONSTRAINT CK_SUB_VALUE   CHECK (CONTRACTED_VALUE > 0)
);

CREATE TABLE TB_CAD_CLINIC (
    ID      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NAME    VARCHAR2(150) NOT NULL,
    CNPJ    VARCHAR2(18)  NOT NULL UNIQUE,
    CITY_ID NUMBER(19)    NOT NULL,
    PHONE   VARCHAR2(20),
    CONSTRAINT FK_CLINIC_CITY FOREIGN KEY (CITY_ID) REFERENCES TB_CAD_CITY(ID)
);

-- =====================================================================
-- Tabelas de saúde e log
-- =====================================================================

CREATE TABLE TB_HEA_CLINICAL_EVENT (
    ID         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PET_ID     NUMBER(19)   NOT NULL,
    CLINIC_ID  NUMBER(19)   NOT NULL,
    EVENT_TYPE VARCHAR2(20) NOT NULL,
    EVENT_DATE TIMESTAMP    NOT NULL,
    STATUS     VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_EVENT_PET    FOREIGN KEY (PET_ID)    REFERENCES TB_CAD_PET(ID),
    CONSTRAINT FK_EVENT_CLINIC FOREIGN KEY (CLINIC_ID) REFERENCES TB_CAD_CLINIC(ID),
    CONSTRAINT CK_EVENT_TYPE   CHECK (EVENT_TYPE IN ('CONSULTATION','VACCINATION','SURGERY','FOLLOW_UP','EXAM')),
    CONSTRAINT CK_EVENT_STATUS CHECK (STATUS IN ('SCHEDULED','COMPLETED','CANCELED'))
);

CREATE TABLE TB_HEA_REMINDER (
    ID       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PET_ID   NUMBER(19)    NOT NULL,
    TITLE    VARCHAR2(150) NOT NULL,
    DUE_DATE DATE          NOT NULL,
    STATUS   VARCHAR2(20)  DEFAULT 'PENDING',
    CONSTRAINT FK_REMINDER_PET    FOREIGN KEY (PET_ID) REFERENCES TB_CAD_PET(ID),
    CONSTRAINT CK_REMINDER_STATUS CHECK (STATUS IN ('PENDING','COMPLETED','CANCELED'))
);

CREATE TABLE TB_HEA_ERROR_LOG (
    ID              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PROCEDURE_NAME  VARCHAR2(100),
    USER_NAME       VARCHAR2(100),
    OCCURRENCE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    ERROR_CODE      VARCHAR2(20),
    ERROR_MESSAGE   VARCHAR2(2000)
);

-- =====================================================================
-- Procedures de carga
-- Cada procedure trata: uma exceção específica, outra exceção específica,
-- e WHEN OTHERS. Os erros são registrados na TB_HEA_ERROR_LOG.
-- =====================================================================

CREATE OR REPLACE PROCEDURE SP_INSERT_SPECIES(p_name IN VARCHAR2) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
BEGIN
    INSERT INTO TB_CAD_SPECIES (NAME) VALUES (p_name);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        v_code := SQLCODE;
        v_msg  := 'Espécie já cadastrada: '||p_name;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_SPECIES',USER,v_code,v_msg);
        COMMIT;
    WHEN VALUE_ERROR THEN
        v_code := SQLCODE;
        v_msg  := 'Nome de espécie inválido: '||p_name;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_SPECIES',USER,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_SPECIES',USER,v_code,v_msg);
        COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_INSERT_BREED(p_species_id IN NUMBER, p_name IN VARCHAR2) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
BEGIN
    INSERT INTO TB_CAD_BREED (SPECIES_ID,NAME) VALUES (p_species_id,p_name);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        v_code := SQLCODE;
        v_msg  := 'Raça já cadastrada para esta espécie: '||p_name;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_BREED',USER,v_code,v_msg);
        COMMIT;
    WHEN VALUE_ERROR THEN
        v_code := SQLCODE;
        v_msg  := 'Dados inválidos para a raça: '||p_name;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_BREED',USER,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_BREED',USER,v_code,v_msg);
        COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_INSERT_STATE(p_uf IN VARCHAR2, p_name IN VARCHAR2) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
BEGIN
    INSERT INTO TB_CAD_STATE (UF,NAME) VALUES (p_uf,p_name);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        v_code := SQLCODE;
        v_msg  := 'Estado já cadastrado: '||p_uf;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_STATE',USER,v_code,v_msg);
        COMMIT;
    WHEN VALUE_ERROR THEN
        v_code := SQLCODE;
        v_msg  := 'UF deve ter 2 caracteres: '||p_uf;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_STATE',USER,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_STATE',USER,v_code,v_msg);
        COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_INSERT_CITY(p_state_id IN NUMBER, p_name IN VARCHAR2) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
BEGIN
    INSERT INTO TB_CAD_CITY (STATE_ID,NAME) VALUES (p_state_id,p_name);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        v_code := SQLCODE;
        v_msg  := 'Cidade já cadastrada neste estado: '||p_name;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_CITY',USER,v_code,v_msg);
        COMMIT;
    WHEN VALUE_ERROR THEN
        v_code := SQLCODE;
        v_msg  := 'Dados inválidos para a cidade: '||p_name;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_CITY',USER,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_CITY',USER,v_code,v_msg);
        COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_INSERT_PAYMENT_METHOD(p_name IN VARCHAR2) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
BEGIN
    INSERT INTO TB_CAD_PAYMENT_METHOD (NAME) VALUES (p_name);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        v_code := SQLCODE;
        v_msg  := 'Método de pagamento já existe: '||p_name;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_PAYMENT_METHOD',USER,v_code,v_msg);
        COMMIT;
    WHEN VALUE_ERROR THEN
        v_code := SQLCODE;
        v_msg  := 'Valor inválido para o método de pagamento';
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_PAYMENT_METHOD',USER,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_PAYMENT_METHOD',USER,v_code,v_msg);
        COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_INSERT_STATUS(p_name IN VARCHAR2) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
BEGIN
    INSERT INTO TB_CAD_SUB_STATUS (NAME) VALUES (p_name);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        v_code := SQLCODE;
        v_msg  := 'Status já existe: '||p_name;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_STATUS',USER,v_code,v_msg);
        COMMIT;
    WHEN VALUE_ERROR THEN
        v_code := SQLCODE;
        v_msg  := 'Valor inválido para o status';
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_STATUS',USER,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_STATUS',USER,v_code,v_msg);
        COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_INSERT_PLAN(p_name IN VARCHAR2, p_value IN NUMBER) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
BEGIN
    INSERT INTO TB_CAD_PLAN (NAME,MONTHLY_VALUE) VALUES (p_name,p_value);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        v_code := SQLCODE;
        v_msg  := 'Plano já existe: '||p_name;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_PLAN',USER,v_code,v_msg);
        COMMIT;
    WHEN INVALID_NUMBER THEN
        v_code := SQLCODE;
        v_msg  := 'Valor mensal não é numérico para o plano: '||p_name;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_PLAN',USER,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_PLAN',USER,v_code,v_msg);
        COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_INSERT_OWNER(
    p_name          IN VARCHAR2,
    p_cpf           IN VARCHAR2,
    p_email         IN VARCHAR2,
    p_password_hash IN VARCHAR2,
    p_phone         IN VARCHAR2,
    p_city_id       IN NUMBER
) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
BEGIN
    INSERT INTO TB_CAD_OWNER (NAME,CPF,EMAIL,PASSWORD_HASH,PHONE,CITY_ID)
    VALUES (p_name,p_cpf,p_email,p_password_hash,p_phone,p_city_id);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        v_code := SQLCODE;
        v_msg  := 'CPF ou email já cadastrado: '||p_cpf||' / '||p_email;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_OWNER',USER,v_code,v_msg);
        COMMIT;
    WHEN VALUE_ERROR THEN
        v_code := SQLCODE;
        v_msg  := 'Dados inválidos para o tutor: '||p_name;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_OWNER',USER,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_OWNER',USER,v_code,v_msg);
        COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_INSERT_PET(
    p_owner_id   IN NUMBER,
    p_species_id IN NUMBER,
    p_breed_id   IN NUMBER,
    p_name       IN VARCHAR2,
    p_birth_date IN DATE,
    p_sex        IN VARCHAR2
) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
BEGIN
    INSERT INTO TB_CAD_PET (OWNER_ID,SPECIES_ID,BREED_ID,NAME,BIRTH_DATE,SEX)
    VALUES (p_owner_id,p_species_id,p_breed_id,p_name,p_birth_date,p_sex);
    COMMIT;
EXCEPTION
    WHEN INVALID_NUMBER THEN
        v_code := SQLCODE;
        v_msg  := 'ID numérico inválido para o pet: '||p_name;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_PET',USER,v_code,v_msg);
        COMMIT;
    WHEN VALUE_ERROR THEN
        v_code := SQLCODE;
        v_msg  := 'Dados inválidos para o pet: '||p_name;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_PET',USER,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_PET',USER,v_code,v_msg);
        COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_INSERT_CLINIC(
    p_name    IN VARCHAR2,
    p_cnpj    IN VARCHAR2,
    p_city_id IN NUMBER,
    p_phone   IN VARCHAR2
) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
BEGIN
    INSERT INTO TB_CAD_CLINIC (NAME,CNPJ,CITY_ID,PHONE)
    VALUES (p_name,p_cnpj,p_city_id,p_phone);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        v_code := SQLCODE;
        v_msg  := 'CNPJ já cadastrado: '||p_cnpj;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_CLINIC',USER,v_code,v_msg);
        COMMIT;
    WHEN VALUE_ERROR THEN
        v_code := SQLCODE;
        v_msg  := 'Dados inválidos para a clínica: '||p_name;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_CLINIC',USER,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_CLINIC',USER,v_code,v_msg);
        COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_INSERT_SUBSCRIPTION(
    p_pet_id            IN NUMBER,
    p_plan_id           IN NUMBER,
    p_status_id         IN NUMBER,
    p_payment_method_id IN NUMBER,
    p_value             IN NUMBER
) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
BEGIN
    INSERT INTO TB_CAD_SUBSCRIPTION (PET_ID,PLAN_ID,STATUS_ID,PAYMENT_METHOD_ID,CONTRACTED_VALUE)
    VALUES (p_pet_id,p_plan_id,p_status_id,p_payment_method_id,p_value);
    COMMIT;
EXCEPTION
    WHEN INVALID_NUMBER THEN
        v_code := SQLCODE;
        v_msg  := 'Valor numérico inválido para assinatura do pet '||p_pet_id;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_SUBSCRIPTION',USER,v_code,v_msg);
        COMMIT;
    WHEN VALUE_ERROR THEN
        v_code := SQLCODE;
        v_msg  := 'Dados inválidos para assinatura do pet '||p_pet_id;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_SUBSCRIPTION',USER,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_SUBSCRIPTION',USER,v_code,v_msg);
        COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_INSERT_EVENT(
    p_pet_id     IN NUMBER,
    p_clinic_id  IN NUMBER,
    p_event_type IN VARCHAR2,
    p_event_date IN TIMESTAMP,
    p_status     IN VARCHAR2
) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
BEGIN
    INSERT INTO TB_HEA_CLINICAL_EVENT (PET_ID,CLINIC_ID,EVENT_TYPE,EVENT_DATE,STATUS)
    VALUES (p_pet_id,p_clinic_id,p_event_type,p_event_date,p_status);
    COMMIT;
EXCEPTION
    WHEN INVALID_NUMBER THEN
        v_code := SQLCODE;
        v_msg  := 'ID numérico inválido para evento clínico';
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_EVENT',USER,v_code,v_msg);
        COMMIT;
    WHEN VALUE_ERROR THEN
        v_code := SQLCODE;
        v_msg  := 'Dados inválidos para evento clínico: '||p_event_type;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_EVENT',USER,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_EVENT',USER,v_code,v_msg);
        COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_INSERT_REMINDER(
    p_pet_id IN NUMBER,
    p_title  IN VARCHAR2,
    p_date   IN DATE,
    p_status IN VARCHAR2
) IS
    v_code VARCHAR2(20);
    v_msg  VARCHAR2(2000);
BEGIN
    INSERT INTO TB_HEA_REMINDER (PET_ID,TITLE,DUE_DATE,STATUS)
    VALUES (p_pet_id,p_title,p_date,p_status);
    COMMIT;
EXCEPTION
    WHEN INVALID_NUMBER THEN
        v_code := SQLCODE;
        v_msg  := 'ID numérico inválido para lembrete';
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_REMINDER',USER,v_code,v_msg);
        COMMIT;
    WHEN VALUE_ERROR THEN
        v_code := SQLCODE;
        v_msg  := 'Dados inválidos para lembrete: '||p_title;
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_REMINDER',USER,v_code,v_msg);
        COMMIT;
    WHEN OTHERS THEN
        v_code := SQLCODE;
        v_msg  := SUBSTR(SQLERRM,1,2000);
        INSERT INTO TB_HEA_ERROR_LOG (PROCEDURE_NAME,USER_NAME,ERROR_CODE,ERROR_MESSAGE)
        VALUES ('SP_INSERT_REMINDER',USER,v_code,v_msg);
        COMMIT;
END;
/

-- =====================================================================
-- Carga de dados via procedures
-- =====================================================================

-- Espécies
BEGIN
    SP_INSERT_SPECIES('Dog');
    SP_INSERT_SPECIES('Cat');
    SP_INSERT_SPECIES('Bird');
    SP_INSERT_SPECIES('Rabbit');
END;
/

-- Raças
DECLARE
    v_dog    NUMBER;
    v_cat    NUMBER;
    v_bird   NUMBER;
    v_rabbit NUMBER;
BEGIN
    SELECT ID INTO v_dog    FROM TB_CAD_SPECIES WHERE NAME = 'Dog';
    SELECT ID INTO v_cat    FROM TB_CAD_SPECIES WHERE NAME = 'Cat';
    SELECT ID INTO v_bird   FROM TB_CAD_SPECIES WHERE NAME = 'Bird';
    SELECT ID INTO v_rabbit FROM TB_CAD_SPECIES WHERE NAME = 'Rabbit';

    SP_INSERT_BREED(v_dog,    'Labrador');
    SP_INSERT_BREED(v_dog,    'Golden Retriever');
    SP_INSERT_BREED(v_dog,    'Bulldog');
    SP_INSERT_BREED(v_dog,    'Poodle');
    SP_INSERT_BREED(v_dog,    'Mixed');
    SP_INSERT_BREED(v_cat,    'Siamese');
    SP_INSERT_BREED(v_cat,    'Persian');
    SP_INSERT_BREED(v_cat,    'Maine Coon');
    SP_INSERT_BREED(v_cat,    'Mixed');
    SP_INSERT_BREED(v_bird,   'Cockatiel');
    SP_INSERT_BREED(v_bird,   'Parakeet');
    SP_INSERT_BREED(v_rabbit, 'Mini Lop');

    -- Tentativa duplicada para gerar log
    SP_INSERT_BREED(v_dog, 'Labrador');
END;
/

-- Estados
BEGIN
    SP_INSERT_STATE('SP','Sao Paulo');
    SP_INSERT_STATE('RJ','Rio de Janeiro');
    SP_INSERT_STATE('MG','Minas Gerais');
    SP_INSERT_STATE('PR','Parana');
    SP_INSERT_STATE('CE','Ceara');
    SP_INSERT_STATE('RS','Rio Grande do Sul');
    SP_INSERT_STATE('BA','Bahia');
    SP_INSERT_STATE('SC','Santa Catarina');
END;
/

-- Cidades
DECLARE
    v_sp NUMBER; v_rj NUMBER; v_mg NUMBER; v_pr NUMBER;
    v_ce NUMBER; v_rs NUMBER; v_ba NUMBER; v_sc NUMBER;
BEGIN
    SELECT ID INTO v_sp FROM TB_CAD_STATE WHERE UF = 'SP';
    SELECT ID INTO v_rj FROM TB_CAD_STATE WHERE UF = 'RJ';
    SELECT ID INTO v_mg FROM TB_CAD_STATE WHERE UF = 'MG';
    SELECT ID INTO v_pr FROM TB_CAD_STATE WHERE UF = 'PR';
    SELECT ID INTO v_ce FROM TB_CAD_STATE WHERE UF = 'CE';
    SELECT ID INTO v_rs FROM TB_CAD_STATE WHERE UF = 'RS';
    SELECT ID INTO v_ba FROM TB_CAD_STATE WHERE UF = 'BA';
    SELECT ID INTO v_sc FROM TB_CAD_STATE WHERE UF = 'SC';

    SP_INSERT_CITY(v_sp, 'Sao Paulo');
    SP_INSERT_CITY(v_sp, 'Campinas');
    SP_INSERT_CITY(v_sp, 'Santos');
    SP_INSERT_CITY(v_rj, 'Rio de Janeiro');
    SP_INSERT_CITY(v_rj, 'Niteroi');
    SP_INSERT_CITY(v_mg, 'Belo Horizonte');
    SP_INSERT_CITY(v_mg, 'Uberlandia');
    SP_INSERT_CITY(v_pr, 'Curitiba');
    SP_INSERT_CITY(v_ce, 'Fortaleza');
    SP_INSERT_CITY(v_rs, 'Porto Alegre');
    SP_INSERT_CITY(v_ba, 'Salvador');
    SP_INSERT_CITY(v_sc, 'Florianopolis');
END;
/

-- Planos
BEGIN
    SP_INSERT_PLAN('Essential',  49.90);
    SP_INSERT_PLAN('Basic',      69.90);
    SP_INSERT_PLAN('Premium',    99.90);
    SP_INSERT_PLAN('Master',    139.90);
    SP_INSERT_PLAN('Total',     179.90);
END;
/

-- Métodos de pagamento
BEGIN
    SP_INSERT_PAYMENT_METHOD('Card');
    SP_INSERT_PAYMENT_METHOD('Pix');
    SP_INSERT_PAYMENT_METHOD('Boleto');
    SP_INSERT_PAYMENT_METHOD('Auto Debit');
END;
/

-- Status de assinatura
BEGIN
    SP_INSERT_STATUS('ACTIVE');
    SP_INSERT_STATUS('CANCELED');
    SP_INSERT_STATUS('SUSPENDED');
    SP_INSERT_STATUS('OVERDUE');
END;
/

-- Tutores (Owners)
DECLARE
    v_sao_paulo    NUMBER;
    v_rio          NUMBER;
    v_bh           NUMBER;
    v_curitiba     NUMBER;
    v_fortaleza    NUMBER;
    v_porto_alegre NUMBER;
    v_salvador     NUMBER;
    v_floripa      NUMBER;
BEGIN
    SELECT ID INTO v_sao_paulo    FROM TB_CAD_CITY WHERE NAME = 'Sao Paulo';
    SELECT ID INTO v_rio          FROM TB_CAD_CITY WHERE NAME = 'Rio de Janeiro';
    SELECT ID INTO v_bh           FROM TB_CAD_CITY WHERE NAME = 'Belo Horizonte';
    SELECT ID INTO v_curitiba     FROM TB_CAD_CITY WHERE NAME = 'Curitiba';
    SELECT ID INTO v_fortaleza    FROM TB_CAD_CITY WHERE NAME = 'Fortaleza';
    SELECT ID INTO v_porto_alegre FROM TB_CAD_CITY WHERE NAME = 'Porto Alegre';
    SELECT ID INTO v_salvador     FROM TB_CAD_CITY WHERE NAME = 'Salvador';
    SELECT ID INTO v_floripa      FROM TB_CAD_CITY WHERE NAME = 'Florianopolis';

    SP_INSERT_OWNER('Ana Paula Souza','111.111.111-11','ana@email.com',     'hash1','(11) 91111-1111', v_sao_paulo);
    SP_INSERT_OWNER('Carlos Menezes', '222.222.222-22','carlos@email.com',  'hash2','(21) 92222-2222', v_rio);
    SP_INSERT_OWNER('Fernanda Lima',  '333.333.333-33','fernanda@email.com','hash3','(31) 93333-3333', v_bh);
    SP_INSERT_OWNER('Ricardo Alves',  '444.444.444-44','ricardo@email.com', 'hash4','(41) 94444-4444', v_curitiba);
    SP_INSERT_OWNER('Mariana Costa',  '555.555.555-55','mariana@email.com', 'hash5','(85) 95555-5555', v_fortaleza);
    SP_INSERT_OWNER('Bruno Tavares',  '666.666.666-66','bruno@email.com',   'hash6','(51) 96666-6666', v_porto_alegre);
    SP_INSERT_OWNER('Juliana Reis',   '777.777.777-77','juliana@email.com', 'hash7','(71) 97777-7777', v_salvador);
    SP_INSERT_OWNER('Pedro Henrique', '888.888.888-88','pedro@email.com',   'hash8','(48) 98888-8888', v_floripa);

    -- Tentativa de CPF duplicado para gerar log
    SP_INSERT_OWNER('Test Duplicate','111.111.111-11','teste@email.com','hash9','(11) 99999-9999', v_sao_paulo);
END;
/

-- Clínicas
DECLARE
    v_sao_paulo    NUMBER;
    v_rio          NUMBER;
    v_bh           NUMBER;
    v_curitiba     NUMBER;
    v_fortaleza    NUMBER;
    v_porto_alegre NUMBER;
BEGIN
    SELECT ID INTO v_sao_paulo    FROM TB_CAD_CITY WHERE NAME = 'Sao Paulo';
    SELECT ID INTO v_rio          FROM TB_CAD_CITY WHERE NAME = 'Rio de Janeiro';
    SELECT ID INTO v_bh           FROM TB_CAD_CITY WHERE NAME = 'Belo Horizonte';
    SELECT ID INTO v_curitiba     FROM TB_CAD_CITY WHERE NAME = 'Curitiba';
    SELECT ID INTO v_fortaleza    FROM TB_CAD_CITY WHERE NAME = 'Fortaleza';
    SELECT ID INTO v_porto_alegre FROM TB_CAD_CITY WHERE NAME = 'Porto Alegre';

    SP_INSERT_CLINIC('Vet Center SP',  '11.111.111/0001-11', v_sao_paulo,    '(11) 3111-1111');
    SP_INSERT_CLINIC('Animal Life RJ', '22.222.222/0001-22', v_rio,          '(21) 3222-2222');
    SP_INSERT_CLINIC('PetHealth BH',   '33.333.333/0001-33', v_bh,           '(31) 3333-3333');
    SP_INSERT_CLINIC('VetClinic PR',   '44.444.444/0001-44', v_curitiba,     '(41) 3444-4444');
    SP_INSERT_CLINIC('Animal Care CE', '55.555.555/0001-55', v_fortaleza,    '(85) 3555-5555');
    SP_INSERT_CLINIC('Pet Life RS',    '66.666.666/0001-66', v_porto_alegre, '(51) 3666-6666');
END;
/

-- Pets
DECLARE
    v_o1 NUMBER; v_o2 NUMBER; v_o3 NUMBER; v_o4 NUMBER;
    v_o5 NUMBER; v_o6 NUMBER; v_o7 NUMBER; v_o8 NUMBER;
    v_dog NUMBER; v_cat NUMBER; v_bird NUMBER; v_rabbit NUMBER;
    v_labrador  NUMBER; v_golden    NUMBER; v_bulldog NUMBER;
    v_poodle    NUMBER; v_mixed_dog NUMBER;
    v_siamese   NUMBER; v_persian   NUMBER; v_mainecoon NUMBER;
    v_cockatiel NUMBER; v_minilop   NUMBER;
BEGIN
    SELECT ID INTO v_o1 FROM TB_CAD_OWNER WHERE CPF = '111.111.111-11';
    SELECT ID INTO v_o2 FROM TB_CAD_OWNER WHERE CPF = '222.222.222-22';
    SELECT ID INTO v_o3 FROM TB_CAD_OWNER WHERE CPF = '333.333.333-33';
    SELECT ID INTO v_o4 FROM TB_CAD_OWNER WHERE CPF = '444.444.444-44';
    SELECT ID INTO v_o5 FROM TB_CAD_OWNER WHERE CPF = '555.555.555-55';
    SELECT ID INTO v_o6 FROM TB_CAD_OWNER WHERE CPF = '666.666.666-66';
    SELECT ID INTO v_o7 FROM TB_CAD_OWNER WHERE CPF = '777.777.777-77';
    SELECT ID INTO v_o8 FROM TB_CAD_OWNER WHERE CPF = '888.888.888-88';

    SELECT ID INTO v_dog    FROM TB_CAD_SPECIES WHERE NAME = 'Dog';
    SELECT ID INTO v_cat    FROM TB_CAD_SPECIES WHERE NAME = 'Cat';
    SELECT ID INTO v_bird   FROM TB_CAD_SPECIES WHERE NAME = 'Bird';
    SELECT ID INTO v_rabbit FROM TB_CAD_SPECIES WHERE NAME = 'Rabbit';

    SELECT ID INTO v_labrador  FROM TB_CAD_BREED WHERE SPECIES_ID = v_dog    AND NAME = 'Labrador';
    SELECT ID INTO v_golden    FROM TB_CAD_BREED WHERE SPECIES_ID = v_dog    AND NAME = 'Golden Retriever';
    SELECT ID INTO v_bulldog   FROM TB_CAD_BREED WHERE SPECIES_ID = v_dog    AND NAME = 'Bulldog';
    SELECT ID INTO v_poodle    FROM TB_CAD_BREED WHERE SPECIES_ID = v_dog    AND NAME = 'Poodle';
    SELECT ID INTO v_mixed_dog FROM TB_CAD_BREED WHERE SPECIES_ID = v_dog    AND NAME = 'Mixed';
    SELECT ID INTO v_siamese   FROM TB_CAD_BREED WHERE SPECIES_ID = v_cat    AND NAME = 'Siamese';
    SELECT ID INTO v_persian   FROM TB_CAD_BREED WHERE SPECIES_ID = v_cat    AND NAME = 'Persian';
    SELECT ID INTO v_mainecoon FROM TB_CAD_BREED WHERE SPECIES_ID = v_cat    AND NAME = 'Maine Coon';
    SELECT ID INTO v_cockatiel FROM TB_CAD_BREED WHERE SPECIES_ID = v_bird   AND NAME = 'Cockatiel';
    SELECT ID INTO v_minilop   FROM TB_CAD_BREED WHERE SPECIES_ID = v_rabbit AND NAME = 'Mini Lop';

    SP_INSERT_PET(v_o1, v_dog,    v_labrador,  'Rex',       DATE '2020-03-10','MALE');
    SP_INSERT_PET(v_o1, v_cat,    v_siamese,   'Mia',       DATE '2021-07-22','FEMALE');
    SP_INSERT_PET(v_o2, v_dog,    v_golden,    'Bolinha',   DATE '2019-11-05','MALE');
    SP_INSERT_PET(v_o3, v_dog,    v_mixed_dog, 'Thor',      DATE '2022-01-15','MALE');
    SP_INSERT_PET(v_o3, v_cat,    v_persian,   'Luna',      DATE '2021-05-30','FEMALE');
    SP_INSERT_PET(v_o4, v_bird,   v_cockatiel, 'Pipoca',    DATE '2023-02-14','FEMALE');
    SP_INSERT_PET(v_o5, v_dog,    v_bulldog,   'Max',       DATE '2018-08-20','MALE');
    SP_INSERT_PET(v_o5, v_cat,    v_mainecoon, 'Nala',      DATE '2020-12-01','FEMALE');
    SP_INSERT_PET(v_o6, v_dog,    v_poodle,    'Toby',      DATE '2022-06-08','MALE');
    SP_INSERT_PET(v_o7, v_rabbit, v_minilop,   'Floquinho', DATE '2023-04-12','MALE');
    SP_INSERT_PET(v_o8, v_cat,    v_persian,   'Estrela',   DATE '2019-09-25','FEMALE');
END;
/

-- Assinaturas
DECLARE
    v_essential NUMBER; v_basic NUMBER; v_premium NUMBER;
    v_master    NUMBER; v_total  NUMBER;
    v_active    NUMBER; v_canceled  NUMBER;
    v_suspended NUMBER; v_overdue   NUMBER;
    v_card      NUMBER; v_pix NUMBER; v_boleto NUMBER; v_debit NUMBER;
    v_p1 NUMBER; v_p2 NUMBER; v_p3 NUMBER; v_p4 NUMBER; v_p5 NUMBER;
    v_p6 NUMBER; v_p7 NUMBER; v_p8 NUMBER; v_p9 NUMBER; v_p10 NUMBER; v_p11 NUMBER;
BEGIN
    SELECT ID INTO v_essential FROM TB_CAD_PLAN WHERE NAME = 'Essential';
    SELECT ID INTO v_basic     FROM TB_CAD_PLAN WHERE NAME = 'Basic';
    SELECT ID INTO v_premium   FROM TB_CAD_PLAN WHERE NAME = 'Premium';
    SELECT ID INTO v_master    FROM TB_CAD_PLAN WHERE NAME = 'Master';
    SELECT ID INTO v_total     FROM TB_CAD_PLAN WHERE NAME = 'Total';

    SELECT ID INTO v_active    FROM TB_CAD_SUB_STATUS WHERE NAME = 'ACTIVE';
    SELECT ID INTO v_canceled  FROM TB_CAD_SUB_STATUS WHERE NAME = 'CANCELED';
    SELECT ID INTO v_suspended FROM TB_CAD_SUB_STATUS WHERE NAME = 'SUSPENDED';
    SELECT ID INTO v_overdue   FROM TB_CAD_SUB_STATUS WHERE NAME = 'OVERDUE';

    SELECT ID INTO v_card   FROM TB_CAD_PAYMENT_METHOD WHERE NAME = 'Card';
    SELECT ID INTO v_pix    FROM TB_CAD_PAYMENT_METHOD WHERE NAME = 'Pix';
    SELECT ID INTO v_boleto FROM TB_CAD_PAYMENT_METHOD WHERE NAME = 'Boleto';
    SELECT ID INTO v_debit  FROM TB_CAD_PAYMENT_METHOD WHERE NAME = 'Auto Debit';

    SELECT ID INTO v_p1  FROM TB_CAD_PET WHERE NAME = 'Rex';
    SELECT ID INTO v_p2  FROM TB_CAD_PET WHERE NAME = 'Mia';
    SELECT ID INTO v_p3  FROM TB_CAD_PET WHERE NAME = 'Bolinha';
    SELECT ID INTO v_p4  FROM TB_CAD_PET WHERE NAME = 'Thor';
    SELECT ID INTO v_p5  FROM TB_CAD_PET WHERE NAME = 'Luna';
    SELECT ID INTO v_p6  FROM TB_CAD_PET WHERE NAME = 'Pipoca';
    SELECT ID INTO v_p7  FROM TB_CAD_PET WHERE NAME = 'Max';
    SELECT ID INTO v_p8  FROM TB_CAD_PET WHERE NAME = 'Nala';
    SELECT ID INTO v_p9  FROM TB_CAD_PET WHERE NAME = 'Toby';
    SELECT ID INTO v_p10 FROM TB_CAD_PET WHERE NAME = 'Floquinho';
    SELECT ID INTO v_p11 FROM TB_CAD_PET WHERE NAME = 'Estrela';

    SP_INSERT_SUBSCRIPTION(v_p1,  v_total,     v_active,    v_card,   179.90);
    SP_INSERT_SUBSCRIPTION(v_p2,  v_premium,   v_active,    v_pix,     99.90);
    SP_INSERT_SUBSCRIPTION(v_p3,  v_essential, v_active,    v_boleto,  49.90);
    SP_INSERT_SUBSCRIPTION(v_p4,  v_premium,   v_canceled,  v_card,    99.90);
    SP_INSERT_SUBSCRIPTION(v_p5,  v_total,     v_active,    v_pix,    179.90);
    SP_INSERT_SUBSCRIPTION(v_p6,  v_essential, v_suspended, v_boleto,  49.90);
    SP_INSERT_SUBSCRIPTION(v_p7,  v_premium,   v_active,    v_card,    99.90);
    SP_INSERT_SUBSCRIPTION(v_p8,  v_master,    v_active,    v_debit,  139.90);
    SP_INSERT_SUBSCRIPTION(v_p9,  v_basic,     v_active,    v_pix,     69.90);
    SP_INSERT_SUBSCRIPTION(v_p10, v_essential, v_overdue,   v_boleto,  49.90);
    SP_INSERT_SUBSCRIPTION(v_p11, v_master,    v_active,    v_card,   139.90);
END;
/

-- Eventos clínicos
DECLARE
    v_p1 NUMBER; v_p2 NUMBER; v_p3 NUMBER; v_p4 NUMBER; v_p5 NUMBER;
    v_p7 NUMBER; v_p8 NUMBER; v_p9 NUMBER; v_p11 NUMBER;
    v_c1 NUMBER; v_c2 NUMBER; v_c3 NUMBER; v_c4 NUMBER; v_c5 NUMBER; v_c6 NUMBER;
BEGIN
    SELECT ID INTO v_p1  FROM TB_CAD_PET WHERE NAME = 'Rex';
    SELECT ID INTO v_p2  FROM TB_CAD_PET WHERE NAME = 'Mia';
    SELECT ID INTO v_p3  FROM TB_CAD_PET WHERE NAME = 'Bolinha';
    SELECT ID INTO v_p4  FROM TB_CAD_PET WHERE NAME = 'Thor';
    SELECT ID INTO v_p5  FROM TB_CAD_PET WHERE NAME = 'Luna';
    SELECT ID INTO v_p7  FROM TB_CAD_PET WHERE NAME = 'Max';
    SELECT ID INTO v_p8  FROM TB_CAD_PET WHERE NAME = 'Nala';
    SELECT ID INTO v_p9  FROM TB_CAD_PET WHERE NAME = 'Toby';
    SELECT ID INTO v_p11 FROM TB_CAD_PET WHERE NAME = 'Estrela';

    SELECT ID INTO v_c1 FROM TB_CAD_CLINIC WHERE CNPJ = '11.111.111/0001-11';
    SELECT ID INTO v_c2 FROM TB_CAD_CLINIC WHERE CNPJ = '22.222.222/0001-22';
    SELECT ID INTO v_c3 FROM TB_CAD_CLINIC WHERE CNPJ = '33.333.333/0001-33';
    SELECT ID INTO v_c4 FROM TB_CAD_CLINIC WHERE CNPJ = '44.444.444/0001-44';
    SELECT ID INTO v_c5 FROM TB_CAD_CLINIC WHERE CNPJ = '55.555.555/0001-55';
    SELECT ID INTO v_c6 FROM TB_CAD_CLINIC WHERE CNPJ = '66.666.666/0001-66';

    SP_INSERT_EVENT(v_p1,  v_c1, 'CONSULTATION', TIMESTAMP '2024-01-10 09:00:00','COMPLETED');
    SP_INSERT_EVENT(v_p1,  v_c1, 'VACCINATION',  TIMESTAMP '2024-03-15 10:30:00','COMPLETED');
    SP_INSERT_EVENT(v_p2,  v_c2, 'CONSULTATION', TIMESTAMP '2024-02-20 14:00:00','COMPLETED');
    SP_INSERT_EVENT(v_p3,  v_c3, 'SURGERY',      TIMESTAMP '2024-04-05 08:00:00','COMPLETED');
    SP_INSERT_EVENT(v_p4,  v_c4, 'FOLLOW_UP',    TIMESTAMP '2024-05-12 11:00:00','SCHEDULED');
    SP_INSERT_EVENT(v_p5,  v_c5, 'CONSULTATION', TIMESTAMP '2024-06-18 15:30:00','COMPLETED');
    SP_INSERT_EVENT(v_p7,  v_c1, 'VACCINATION',  TIMESTAMP '2024-07-22 09:45:00','COMPLETED');
    SP_INSERT_EVENT(v_p8,  v_c2, 'CONSULTATION', TIMESTAMP '2024-08-30 13:00:00','SCHEDULED');
    SP_INSERT_EVENT(v_p9,  v_c6, 'EXAM',         TIMESTAMP '2024-09-15 16:00:00','COMPLETED');
    SP_INSERT_EVENT(v_p11, v_c3, 'CONSULTATION', TIMESTAMP '2024-10-10 10:15:00','COMPLETED');
END;
/

-- Lembretes
DECLARE
    v_p1 NUMBER; v_p2 NUMBER; v_p3 NUMBER;
    v_p5 NUMBER; v_p7 NUMBER; v_p9 NUMBER; v_p11 NUMBER;
BEGIN
    SELECT ID INTO v_p1  FROM TB_CAD_PET WHERE NAME = 'Rex';
    SELECT ID INTO v_p2  FROM TB_CAD_PET WHERE NAME = 'Mia';
    SELECT ID INTO v_p3  FROM TB_CAD_PET WHERE NAME = 'Bolinha';
    SELECT ID INTO v_p5  FROM TB_CAD_PET WHERE NAME = 'Luna';
    SELECT ID INTO v_p7  FROM TB_CAD_PET WHERE NAME = 'Max';
    SELECT ID INTO v_p9  FROM TB_CAD_PET WHERE NAME = 'Toby';
    SELECT ID INTO v_p11 FROM TB_CAD_PET WHERE NAME = 'Estrela';

    SP_INSERT_REMINDER(v_p1,  'Annual V10 vaccine',     DATE '2025-03-10','PENDING');
    SP_INSERT_REMINDER(v_p2,  'Monthly flea treatment', DATE '2025-02-01','PENDING');
    SP_INSERT_REMINDER(v_p3,  'Post-surgery follow-up', DATE '2024-04-19','COMPLETED');
    SP_INSERT_REMINDER(v_p5,  'Dermatology consult',    DATE '2025-01-15','PENDING');
    SP_INSERT_REMINDER(v_p7,  'Rabies vaccine',         DATE '2025-07-22','PENDING');
    SP_INSERT_REMINDER(v_p9,  'Bath and grooming',      DATE '2025-05-30','PENDING');
    SP_INSERT_REMINDER(v_p11, 'Feline triple vaccine',  DATE '2025-08-10','PENDING');
END;
/

-- =====================================================================
-- Bloco de Join 1: análises comerciais
-- =====================================================================
DECLARE
BEGIN
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE('         BLOCO JOIN 1 - ANÁLISES COMERCIAIS          ');
    DBMS_OUTPUT.PUT_LINE('=====================================================');

    -- Query 1: assinaturas por plano
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('--- Query 1: assinaturas por plano ---');
    DBMS_OUTPUT.PUT_LINE(RPAD('Plano',14)||RPAD('Qtd',6)||RPAD('Receita',16)||'Ticket Médio');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',55,'-'));
    FOR r IN (
        SELECT p.NAME AS plan,
               COUNT(s.ID) AS qty,
               SUM(s.CONTRACTED_VALUE) AS revenue,
               ROUND(AVG(s.CONTRACTED_VALUE),2) AS ticket
        FROM TB_CAD_SUBSCRIPTION s
        JOIN TB_CAD_PLAN p ON p.ID = s.PLAN_ID
        GROUP BY p.NAME
        ORDER BY revenue DESC
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(RPAD(r.plan,14)||RPAD(r.qty,6)||
            RPAD('R$ '||TO_CHAR(r.revenue,'FM99990.00'),16)||
            'R$ '||TO_CHAR(r.ticket,'FM99990.00'));
    END LOOP;

    -- Query 2: assinaturas por método de pagamento
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('--- Query 2: assinaturas por método de pagamento ---');
    DBMS_OUTPUT.PUT_LINE(RPAD('Método',20)||RPAD('Qtd',6)||'Total');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',45,'-'));
    FOR r IN (
        SELECT pm.NAME AS method,
               COUNT(s.ID) AS qty,
               SUM(s.CONTRACTED_VALUE) AS total
        FROM TB_CAD_SUBSCRIPTION s
        JOIN TB_CAD_PAYMENT_METHOD pm ON pm.ID = s.PAYMENT_METHOD_ID
        GROUP BY pm.NAME
        ORDER BY qty DESC, total DESC
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(RPAD(r.method,20)||RPAD(r.qty,6)||
            'R$ '||TO_CHAR(r.total,'FM99990.00'));
    END LOOP;

    -- Query 3: pets por espécie e status
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('--- Query 3: pets por espécie e status ---');
    DBMS_OUTPUT.PUT_LINE(RPAD('Espécie',12)||RPAD('Status',16)||'Qtd');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',40,'-'));
    FOR r IN (
        SELECT e.NAME AS species,
               st.NAME AS status,
               COUNT(p.ID) AS qty
        FROM TB_CAD_PET p
        JOIN TB_CAD_SPECIES e ON e.ID = p.SPECIES_ID
        JOIN TB_CAD_SUBSCRIPTION s ON s.PET_ID = p.ID
        JOIN TB_CAD_SUB_STATUS st ON st.ID = s.STATUS_ID
        GROUP BY e.NAME, st.NAME
        ORDER BY e.NAME, st.NAME
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(RPAD(r.species,12)||RPAD(r.status,16)||r.qty);
    END LOOP;
END;
/

-- =====================================================================
-- Bloco de Join 2: análises operacionais
-- =====================================================================
DECLARE
BEGIN
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE('        BLOCO JOIN 2 - ANÁLISES OPERACIONAIS         ');
    DBMS_OUTPUT.PUT_LINE('=====================================================');

    -- Query 4: eventos por clínica e tipo
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('--- Query 4: eventos por clínica e tipo ---');
    DBMS_OUTPUT.PUT_LINE(RPAD('Clínica',22)||RPAD('Tipo',14)||RPAD('Qtd',6)||'Últ. Evento');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',60,'-'));
    FOR r IN (
        SELECT cl.NAME AS clinic,
               ec.EVENT_TYPE,
               COUNT(ec.ID) AS qty,
               MAX(ec.EVENT_DATE) AS last_event
        FROM TB_HEA_CLINICAL_EVENT ec
        JOIN TB_CAD_CLINIC cl ON cl.ID = ec.CLINIC_ID
        GROUP BY cl.NAME, ec.EVENT_TYPE
        ORDER BY cl.NAME, ec.EVENT_TYPE
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(RPAD(r.clinic,22)||RPAD(r.event_type,14)||
            RPAD(r.qty,6)||TO_CHAR(r.last_event,'DD/MM/YYYY'));
    END LOOP;

    -- Query 5: tutores com mais de 1 pet
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('--- Query 5: tutores com mais de 1 pet ---');
    DBMS_OUTPUT.PUT_LINE(RPAD('Tutor',22)||RPAD('Cidade',18)||'Qtd Pets');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',50,'-'));
    FOR r IN (
        SELECT o.NAME AS owner,
               c.NAME AS city,
               COUNT(p.ID) AS pet_count
        FROM TB_CAD_OWNER o
        JOIN TB_CAD_CITY c ON c.ID = o.CITY_ID
        JOIN TB_CAD_PET p ON p.OWNER_ID = o.ID
        GROUP BY o.NAME, c.NAME
        HAVING COUNT(p.ID) > 1
        ORDER BY pet_count DESC, o.NAME
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(RPAD(r.owner,22)||RPAD(r.city,18)||r.pet_count);
    END LOOP;

    -- Query 6: lembretes pendentes por tutor
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('--- Query 6: lembretes pendentes por tutor ---');
    DBMS_OUTPUT.PUT_LINE(RPAD('Tutor',22)||RPAD('Qtd',6)||'Próximo');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',45,'-'));
    FOR r IN (
        SELECT o.NAME AS owner,
               COUNT(l.ID) AS qty,
               MIN(l.DUE_DATE) AS next_due
        FROM TB_CAD_OWNER o
        JOIN TB_CAD_PET p ON p.OWNER_ID = o.ID
        JOIN TB_HEA_REMINDER l ON l.PET_ID = p.ID
        WHERE l.STATUS = 'PENDING'
        GROUP BY o.NAME
        ORDER BY next_due
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(RPAD(r.owner,22)||RPAD(r.qty,6)||
            TO_CHAR(r.next_due,'DD/MM/YYYY'));
    END LOOP;
END;
/

-- =====================================================================
-- Relatório LAG / LEAD: valor anterior, atual e próximo
-- =====================================================================
DECLARE
BEGIN
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE('  LAG / LEAD - VALOR ANTERIOR / ATUAL / PRÓXIMO      ');
    DBMS_OUTPUT.PUT_LINE('=====================================================');

    -- Assinaturas em ordem cronológica
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('--- Assinaturas em ordem cronológica ---');
    DBMS_OUTPUT.PUT_LINE(RPAD('Pet',12)||RPAD('Plano',12)||
        RPAD('Vlr.Anterior',14)||RPAD('Vlr.Atual',14)||RPAD('Vlr.Próximo',14)||'Data');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',80,'-'));
    FOR r IN (
        SELECT p.NAME AS pet,
               pl.NAME AS plan,
               s.START_DATE,
               s.CONTRACTED_VALUE AS curr_value,
               LAG(s.CONTRACTED_VALUE)  OVER (ORDER BY s.START_DATE, s.ID) AS prev_value,
               LEAD(s.CONTRACTED_VALUE) OVER (ORDER BY s.START_DATE, s.ID) AS next_value
        FROM TB_CAD_SUBSCRIPTION s
        JOIN TB_CAD_PET p ON p.ID = s.PET_ID
        JOIN TB_CAD_PLAN pl ON pl.ID = s.PLAN_ID
        ORDER BY s.START_DATE, s.ID
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(
            RPAD(r.pet,12)||RPAD(r.plan,12)||
            RPAD(NVL('R$ '||TO_CHAR(r.prev_value,'FM990.00'),'---'),14)||
            RPAD('R$ '||TO_CHAR(r.curr_value,'FM990.00'),14)||
            RPAD(NVL('R$ '||TO_CHAR(r.next_value,'FM990.00'),'---'),14)||
            TO_CHAR(r.start_date,'DD/MM/YYYY'));
    END LOOP;

    -- Planos em ordem de valor
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('--- Planos em ordem de valor ---');
    DBMS_OUTPUT.PUT_LINE(RPAD('Plano Ant',14)||RPAD('R$ Ant',12)||
        RPAD('Plano Atual',14)||RPAD('R$ Atual',12)||
        RPAD('Prox Plano',14)||'R$ Prox');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',78,'-'));
    FOR r IN (
        SELECT NAME AS curr_plan,
               MONTHLY_VALUE AS curr_value,
               LAG(NAME)          OVER (ORDER BY MONTHLY_VALUE) AS prev_plan,
               LAG(MONTHLY_VALUE) OVER (ORDER BY MONTHLY_VALUE) AS prev_value,
               LEAD(NAME)          OVER (ORDER BY MONTHLY_VALUE) AS next_plan,
               LEAD(MONTHLY_VALUE) OVER (ORDER BY MONTHLY_VALUE) AS next_value
        FROM TB_CAD_PLAN
        ORDER BY MONTHLY_VALUE
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(
            RPAD(NVL(r.prev_plan,'---'),14)||
            RPAD(NVL(TO_CHAR(r.prev_value,'FM990.00'),'---'),12)||
            RPAD(r.curr_plan,14)||
            RPAD(TO_CHAR(r.curr_value,'FM990.00'),12)||
            RPAD(NVL(r.next_plan,'---'),14)||
            NVL(TO_CHAR(r.next_value,'FM990.00'),'---'));
    END LOOP;
END;
/

-- =====================================================================
-- Cursor explícito 1: pets ativos com categorização de valor
-- =====================================================================
DECLARE
    CURSOR c_active_pets IS
        SELECT p.NAME AS pet, e.NAME AS species, o.NAME AS owner,
               pl.NAME AS plan, s.CONTRACTED_VALUE
        FROM TB_CAD_PET p
        JOIN TB_CAD_SPECIES e ON e.ID = p.SPECIES_ID
        JOIN TB_CAD_OWNER o ON o.ID = p.OWNER_ID
        JOIN TB_CAD_SUBSCRIPTION s ON s.PET_ID = p.ID
        JOIN TB_CAD_PLAN pl ON pl.ID = s.PLAN_ID
        JOIN TB_CAD_SUB_STATUS st ON st.ID = s.STATUS_ID
        WHERE st.NAME = 'ACTIVE'
        ORDER BY s.CONTRACTED_VALUE DESC;

    v_category   VARCHAR2(20);
    v_total      NUMBER := 0;
    v_count      NUMBER := 0;
    v_count_prem NUMBER := 0;
    v_count_int  NUMBER := 0;
    v_count_bas  NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE('   CURSOR 1 - PETS ATIVOS COM CATEGORIZAÇÃO          ');
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE(RPAD('Pet',12)||RPAD('Espécie',12)||RPAD('Tutor',20)||
        RPAD('Plano',12)||RPAD('Valor',12)||'Categoria');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',80,'-'));

    FOR reg IN c_active_pets LOOP
        -- Tomada de decisão: faixa de valor
        IF reg.CONTRACTED_VALUE >= 150 THEN
            v_category   := 'Premium+';
            v_count_prem := v_count_prem + 1;
        ELSIF reg.CONTRACTED_VALUE >= 80 THEN
            v_category  := 'Intermediário';
            v_count_int := v_count_int + 1;
        ELSE
            v_category  := 'Básico';
            v_count_bas := v_count_bas + 1;
        END IF;

        DBMS_OUTPUT.PUT_LINE(RPAD(reg.pet,12)||RPAD(reg.species,12)||
            RPAD(reg.owner,20)||RPAD(reg.plan,12)||
            RPAD('R$ '||TO_CHAR(reg.CONTRACTED_VALUE,'FM990.00'),12)||v_category);

        v_total := v_total + reg.CONTRACTED_VALUE;
        v_count := v_count + 1;
    END LOOP;

    -- Resumo
    DBMS_OUTPUT.PUT_LINE(RPAD('-',80,'-'));
    DBMS_OUTPUT.PUT_LINE('Total de pets ativos: '||v_count);
    DBMS_OUTPUT.PUT_LINE('  Premium+:     '||v_count_prem);
    DBMS_OUTPUT.PUT_LINE('  Intermediário: '||v_count_int);
    DBMS_OUTPUT.PUT_LINE('  Básico:        '||v_count_bas);
    DBMS_OUTPUT.PUT_LINE('Receita total ativa: R$ '||TO_CHAR(v_total,'FM99990.00'));
END;
/

-- =====================================================================
-- Cursor explícito 2: lembretes com classificação de alerta
-- =====================================================================
DECLARE
    CURSOR c_reminders IS
        SELECT l.TITLE, l.DUE_DATE, l.STATUS,
               p.NAME AS pet, o.NAME AS owner
        FROM TB_HEA_REMINDER l
        JOIN TB_CAD_PET p ON p.ID = l.PET_ID
        JOIN TB_CAD_OWNER o ON o.ID = p.OWNER_ID
        ORDER BY l.STATUS, l.DUE_DATE;

    v_alert      VARCHAR2(20);
    v_pending    NUMBER := 0;
    v_completed  NUMBER := 0;
    v_overdue    NUMBER := 0;
    v_upcoming   NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE('   CURSOR 2 - LEMBRETES COM CLASSIFICAÇÃO DE ALERTA  ');
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE(RPAD('Título',28)||RPAD('Pet',12)||RPAD('Data',14)||
        RPAD('Status',12)||'Alerta');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',80,'-'));

    FOR reg IN c_reminders LOOP
        -- Tomada de decisão: definir alerta com base no status e data
        IF reg.STATUS = 'PENDING' THEN
            v_pending := v_pending + 1;
            IF reg.DUE_DATE < SYSDATE THEN
                v_alert   := 'ATRASADO';
                v_overdue := v_overdue + 1;
            ELSIF reg.DUE_DATE <= SYSDATE + 30 THEN
                v_alert    := 'PRÓXIMO';
                v_upcoming := v_upcoming + 1;
            ELSE
                v_alert := 'OK';
            END IF;
        ELSE
            v_completed := v_completed + 1;
            v_alert     := '-';
        END IF;

        DBMS_OUTPUT.PUT_LINE(RPAD(reg.TITLE,28)||RPAD(reg.pet,12)||
            RPAD(TO_CHAR(reg.DUE_DATE,'DD/MM/YYYY'),14)||
            RPAD(reg.STATUS,12)||v_alert);
    END LOOP;

    -- Resumo
    DBMS_OUTPUT.PUT_LINE(RPAD('-',80,'-'));
    DBMS_OUTPUT.PUT_LINE('Pendentes:  '||v_pending||'   Concluídos: '||v_completed);
    DBMS_OUTPUT.PUT_LINE('Atrasados:  '||v_overdue||'   Próximos (30d): '||v_upcoming);
END;
/

-- =====================================================================
-- Cursor explícito 3: histórico de eventos por pet (quebra de grupo)
-- =====================================================================
DECLARE
    CURSOR c_events IS
        SELECT p.NAME AS pet, e.NAME AS species, cl.NAME AS clinic,
               ec.EVENT_TYPE, ec.STATUS AS event_status, ec.EVENT_DATE
        FROM TB_HEA_CLINICAL_EVENT ec
        JOIN TB_CAD_PET p ON p.ID = ec.PET_ID
        JOIN TB_CAD_SPECIES e ON e.ID = p.SPECIES_ID
        JOIN TB_CAD_CLINIC cl ON cl.ID = ec.CLINIC_ID
        ORDER BY p.NAME, ec.EVENT_DATE;

    v_current_pet VARCHAR2(100) := NULL;
    v_pet_total   NUMBER := 0;
    v_grand_total NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE('   CURSOR 3 - HISTÓRICO DE EVENTOS POR PET           ');
    DBMS_OUTPUT.PUT_LINE('=====================================================');

    FOR reg IN c_events LOOP
        -- Tomada de decisão: detectar mudança de pet para imprimir cabeçalho
        IF v_current_pet IS NULL OR reg.pet <> v_current_pet THEN
            IF v_current_pet IS NOT NULL THEN
                DBMS_OUTPUT.PUT_LINE('  Subtotal '||v_current_pet||': '||v_pet_total||' evento(s)');
                DBMS_OUTPUT.PUT_LINE('');
            END IF;
            v_current_pet := reg.pet;
            v_pet_total   := 0;
            DBMS_OUTPUT.PUT_LINE('--- '||reg.pet||' ('||reg.species||') ---');
        END IF;

        DBMS_OUTPUT.PUT_LINE('  '||RPAD(TO_CHAR(reg.EVENT_DATE,'DD/MM/YYYY'),14)||
            RPAD(reg.event_type,14)||RPAD(reg.clinic,22)||reg.event_status);

        v_pet_total   := v_pet_total + 1;
        v_grand_total := v_grand_total + 1;
    END LOOP;

    -- Imprimir subtotal do último grupo
    IF v_current_pet IS NOT NULL THEN
        DBMS_OUTPUT.PUT_LINE('  Subtotal '||v_current_pet||': '||v_pet_total||' evento(s)');
    END IF;

    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('Total geral: '||v_grand_total||' eventos');
END;
/

-- =====================================================================
-- Cursor explícito 4: receita por estado com ranqueamento
-- =====================================================================
DECLARE
    CURSOR c_state_revenue IS
        SELECT st.NAME AS state, st.UF,
               COUNT(s.ID) AS qty,
               SUM(s.CONTRACTED_VALUE) AS revenue
        FROM TB_CAD_SUBSCRIPTION s
        JOIN TB_CAD_PET p ON p.ID = s.PET_ID
        JOIN TB_CAD_OWNER o ON o.ID = p.OWNER_ID
        JOIN TB_CAD_CITY c ON c.ID = o.CITY_ID
        JOIN TB_CAD_STATE st ON st.ID = c.STATE_ID
        GROUP BY st.NAME, st.UF
        ORDER BY revenue DESC;

    v_rank        NUMBER := 0;
    v_total       NUMBER := 0;
    v_performance VARCHAR2(10);
    v_high        NUMBER := 0;
    v_mid         NUMBER := 0;
    v_low         NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE('   CURSOR 4 - RECEITA POR ESTADO COM RANQUEAMENTO    ');
    DBMS_OUTPUT.PUT_LINE('=====================================================');
    DBMS_OUTPUT.PUT_LINE(RPAD('Rank',6)||RPAD('UF',5)||RPAD('Estado',22)||
        RPAD('Contratos',12)||RPAD('Receita',16)||'Desempenho');
    DBMS_OUTPUT.PUT_LINE(RPAD('-',80,'-'));

    FOR reg IN c_state_revenue LOOP
        v_rank := v_rank + 1;

        -- Tomada de decisão: classificar desempenho
        IF reg.revenue >= 300 THEN
            v_performance := 'Alto';
            v_high        := v_high + 1;
        ELSIF reg.revenue >= 150 THEN
            v_performance := 'Médio';
            v_mid         := v_mid + 1;
        ELSE
            v_performance := 'Baixo';
            v_low         := v_low + 1;
        END IF;

        DBMS_OUTPUT.PUT_LINE(RPAD(v_rank,6)||RPAD(reg.UF,5)||RPAD(reg.state,22)||
            RPAD(reg.qty,12)||
            RPAD('R$ '||TO_CHAR(reg.revenue,'FM99990.00'),16)||v_performance);

        v_total := v_total + reg.revenue;
    END LOOP;

    -- Resumo
    DBMS_OUTPUT.PUT_LINE(RPAD('-',80,'-'));
    DBMS_OUTPUT.PUT_LINE('Receita total: R$ '||TO_CHAR(v_total,'FM99990.00'));
    DBMS_OUTPUT.PUT_LINE('Estados de alto desempenho:   '||v_high);
    DBMS_OUTPUT.PUT_LINE('Estados de médio desempenho: '||v_mid);
    DBMS_OUTPUT.PUT_LINE('Estados de baixo desempenho:    '||v_low);
END;
/


